DROP DATABASE IF EXISTS foro;

CREATE DATABASE IF NOT EXISTS foro;

USE foro;

CREATE TABLE users(
	name_user VARCHAR(16) PRIMARY KEY,
	pass VARCHAR(32) NOT NULL,
	email VARCHAR(32) NOT NULL,
	nombre VARCHAR(24) NOT NULL,
	apellido VARCHAR(24) NOT NULL
);

CREATE TABLE post(
	titulo VARCHAR(32) PRIMARY KEY,
	cuerpo TEXT NOT NULL,
	fecha DATETIME NOT NULL,
	user VARCHAR(16) NOT NULL,
	url VARCHAR(64) NOT NULL,
	FULLTEXT KEY search(titulo,user),
	FOREIGN KEY (user) REFERENCES users(name_user) 
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE comentario(
	titulo VARCHAR(32) PRIMARY KEY,
	fecha DATETIME NOT NULL,
	user VARCHAR(16) NOT NULL,
	FOREIGN KEY (user) REFERENCES users(name_user),
	FOREIGN KEY (titulo) REFERENCES post(titulo)
	ON UPDATE CASCADE ON DELETE CASCADE
);