DROP DATABASE IF EXISTS foro;

CREATE DATABASE IF NOT EXISTS foro;

USE foro;

CREATE TABLE users(
	name_user VARCHAR(16) PRIMARY KEY,
	pass VARCHAR(32) NOT NULL,
	email VARCHAR(32) NOT NULL,
	nombre VARCHAR(24) NOT NULL,
	puntos INT NOT NULL,
	estado BOOLEAN NOT NULL,
	rango VARCHAR(20) NOT NULL,
	apellido VARCHAR(24) NOT NULL,
	fecha DATETIME NOT NULL,
	img_perfil LONGBLOB,
	img_portada LONGBLOB
);

CREATE TABLE post(
	url VARCHAR(64) PRIMARY KEY,
	titulo VARCHAR(32) NOT NULL,
	cuerpo LONGBLOB NOT NULL,
	fecha DATETIME NOT NULL,
	user VARCHAR(16) NOT NULL,
	FULLTEXT KEY search(titulo,user),
	FOREIGN KEY (user) REFERENCES users(name_user) 
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE comentario(
	id_comet INT PRIMARY KEY AUTO_INCREMENT,
	url VARCHAR(32) NOT NULL,
	fecha DATETIME NOT NULL,
	user VARCHAR(16) NOT NULL,
	contenido VARCHAR(300) NOT NULL,
	FOREIGN KEY (user) REFERENCES users(name_user),
	FOREIGN KEY (url) REFERENCES post(url)
	ON UPDATE CASCADE ON DELETE CASCADE
);